// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUGaPDSXrAtKFBpH1bOt7Y8sI7yVhVb_I',
    appId: '1:878699620535:web:4051d7c3eb3c10a6170532',
    messagingSenderId: '878699620535',
    projectId: 'llmpath-28580',
    authDomain: 'llmpath-28580.firebaseapp.com',
    storageBucket: 'llmpath-28580.firebasestorage.app',
    measurementId: 'G-9TNLBPF1CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDFTyAxiYhVo0x1-4Z5OhocbptbFN8xxk',
    appId: '1:878699620535:android:8c4f646a4aed4c0e170532',
    messagingSenderId: '878699620535',
    projectId: 'llmpath-28580',
    storageBucket: 'llmpath-28580.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNvb1kyKXr8Vl3R8EdaFt656Jz6TpYrf8',
    appId: '1:878699620535:ios:246badbd8794da8e170532',
    messagingSenderId: '878699620535',
    projectId: 'llmpath-28580',
    storageBucket: 'llmpath-28580.firebasestorage.app',
    iosBundleId: 'com.example.llmpath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNvb1kyKXr8Vl3R8EdaFt656Jz6TpYrf8',
    appId: '1:878699620535:ios:246badbd8794da8e170532',
    messagingSenderId: '878699620535',
    projectId: 'llmpath-28580',
    storageBucket: 'llmpath-28580.firebasestorage.app',
    iosBundleId: 'com.example.llmpath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUGaPDSXrAtKFBpH1bOt7Y8sI7yVhVb_I',
    appId: '1:878699620535:web:0925160b5bca3c29170532',
    messagingSenderId: '878699620535',
    projectId: 'llmpath-28580',
    authDomain: 'llmpath-28580.firebaseapp.com',
    storageBucket: 'llmpath-28580.firebasestorage.app',
    measurementId: 'G-5ECCG6HZ2Q',
  );
}
